name: interfaz_uno_aiq
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/AIQ_LOGO.png
    - assets/Avion-one.png
    - assets/airbus.png

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/AvenirLTStd-Black.otf
